<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skipped="1" tests="3" time="0.095"><testcase classname="ExampleTest.SimpleTest" file="ExampleTest.py" line="14" name="test_fail" time="0.001"><failure message="AssertionError: 11 != 10">self = &lt;ExampleTest.SimpleTest testMethod=test_fail&gt;

    def test_fail(self):
&gt;       self.assertEqual(11, 7 + 3)
E       AssertionError: 11 != 10

ExampleTest.py:16: AssertionError</failure></testcase><testcase classname="ExampleTest.SimpleTest" file="ExampleTest.py" line="11" name="test_pass" time="0.001"></testcase><testcase classname="ExampleTest.SimpleTest" file="ExampleTest.py" line="7" name="test_skipped" time="0.001"><skipped message="demonstrating skipping" type="pytest.skip">ExampleTest.py:7: demonstrating skipping</skipped></testcase></testsuite>